### ISSUE TITLE
AppVeyor (Windows) throws `Cannot read property 'toLowerCase' of undefined`

### ISSUE THREAD

**Issue by ntwb** [chalk/chalk#164]
Via a chalk 2.0.0 pull request I'm seeing ~300 instances of the following error for stylelint on our Windows AppVeyor builds:

```shell
 FAIL  lib\rules\selector-max-empty-lines\__tests__\index.js
  ● Test suite failed to run
    TypeError: Cannot read property 'toLowerCase' of undefined
      
      at Object.<anonymous> (node_modules/chalk/index.js:8:78)
      at Object.<anonymous> (lib/formatters/stringFormatter.js:5:15)
      at Object.<anonymous> (lib/formatters/index.js:5:11)
 FAIL  lib\rules\selector-no-qualifying-type\__tests__\index.js
```

• chalk ref: https://github.com/chalk/chalk/blob/master/index.js#L8
• stylelint AppVeyor build: https://ci.appveyor.com/project/stylelint/stylelint/build/4476
• stylelint pull request / issue: https://github.com/stylelint/stylelint/pull/2695

**Comment by mymattcarroll** [comment]
Thanks to some investigation by @simonmarklar (only dev in our office with a windows machine), our tests seem to be failing due to `process.env.TERM` not being set.

**Comment by 1mike12** [comment]
samesies. Just happened to me. Windows 10 in powershell. Wanted to use that sweet chalk.keyword() :(

I'll roll it back to chalk 1.1.3

**Comment by Qix-** [comment]
Very interesting. I'm pretty sure that didn't change since the last major version.

Will fix it :) Good catch.

**Comment by Qix-** [comment]
Can you try the latest master?

**Comment by Qix-** [comment]
Released a fix as `2.0.1`. Let me know if that fixed it!

**Comment by DerivcoHK** [comment]
nope.
```
[11:37:26][Step 1/4] M:\TeamCity\buildAgent\work\Titanium\ti\node_modules\run-sequence\node_modules\chalk\index.js:8
[11:37:26][Step 1/4] const isSimpleWindowsTerm = process.platform === 'win32' && !process.env.TERM.toLowerCase().startsWith('xterm');
[11:37:26][Step 1/4]                                                                              ^
[11:37:26][Step 1/4] 
[11:37:26][Step 1/4] TypeError: Cannot read property 'toLowerCase' of undefined
[11:37:26][Step 1/4]     at Object.<anonymous> (M:\TeamCity\buildAgent\work\Titanium\ti\node_modules\run-sequence\node_modules\chalk\index.js:8:78)
[11:37:26][Step 1/4]     at Module._compile (module.js:434:26)
[11:37:26][Step 1/4]     at Object.Module._extensions..js (module.js:452:10)
[11:37:26][Step 1/4]     at Module.load (module.js:355:32)

**Comment by Qix-** [comment]
@DerivcoHK Doesn't look like you updated. Make you're you're up to 2.0.1.

**Comment by ntwb** [comment]
Woot, works for me, thanks for the speedy turn around chalk'rs, appreciated 😄 

Here's the latest AppVeyor build using chalk 2.0.1:
> https://ci.appveyor.com/project/stylelint/stylelint/build/4477

**Comment by 1mike12** [comment]
@Qix- damn you guys are quick, thanks!
