### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by prassh123** [chalk/chalk#168]
The latest package uses strict mode along with a const. This is causing our builds to fail with the error:

src/main/ui/node_modules/run-sequence/node_modules/chalk/index.js:2
const escapeStringRegexp = require('escape-string-regexp');

SyntaxError: Use of const in strict mode.
[12:50:50]     at Module._compile (module.js:439:25)
[12:50:50]     at Object.Module._extensions..js (module.js:474:10)
[12:50:50]     at Module.load (module.js:356:32)
[12:50:50]     at Function.Module._load (module.js:312:12)
[12:50:50]     at Module.require (module.js:364:17)
[12:50:50]     at require (module.js:380:17)
[12:50:50]     at Object.<anonymous>
[12:50:50]     at Module._compile (module.js:456:26)
[12:50:50]     at Object.Module._extensions..js (module.js:474:10)
[12:50:50]     at Module.load (module.js:356:32)
[12:50:50]     at Function.Module._load (module.js:312:12)
[12:50:50]     at Module.require (module.js:364:17)
[12:50:50]     at require (module.js:380:17)
[12:50:50]     at Object.<anonymous>
[12:50:50]     at Module._compile (module.js:456:26)
[12:50:52]     at Object.Module._extensions..js (module.js:474:10)

**Comment by sindresorhus** [comment]
Please read the release notes: https://github.com/chalk/chalk/releases/tag/v2.0.0 Node.js 4 or later is required.
