### ISSUE TITLE
TypeError: _chalk.default.whiteBright is not a function

### ISSUE THREAD

**Issue by devprashin** [chalk/chalk#340]
When I run Webdriver.io project on Jenkins Server, I encounter following error,

/home/workspace/TestBootWizard/node_modules/@wdio/logger/build/node.js:120
  nameFormatter: name => _chalk.default.whiteBright(name)
                                        ^

TypeError: _chalk.default.whiteBright is not a function
    at Object.nameFormatter (/home/jenkins/workspace/TestBootWizard/node_modules/@wdio/logger/build/node.js:120:41)
    at Logger.<anonymous> (/home/jenkins/workspace/TestBootWizard/node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:77:62)
    at launch (/home/workspace/TestBootWizard/node_modules/@wdio/cli/build/run.js:91:7)
    at run (/home/workspace/TestBootWizard/node_modules/@wdio/cli/build/run.js:68:12)
    at Object.run (/home/workspace/TestBootWizard/node_modules/@wdio/cli/build/index.js:45:20)
    at Object.<anonymous> (/home/workspace/TestBootWizard/node_modules/@wdio/cli/bin/wdio.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

**Comment by devprashin** [comment]
` "@wdio/cli": "^5.7.14"`
`"chalk": "2.4.2"`

**Comment by sindresorhus** [comment]
I just tested that Chalk version with the following and it works fine:

```js
const chalk = require('chalk');

chalk.whiteBright('foo');
```

Happy to look into it furtger if you submit a pull request with a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests).

**Comment by akash-jivani** [comment]
I have created on function in typescript file and use chalk as a warning and error log as below 

 import chalk from "chalk";
console.warn(chalk.bgRed.underline("[WARN] Error while "))

In my windows system cmd it is showing color code but in jenkins it is not showing the color.

In Jenkins I have use ansiColor('xterm') but still I can't see the color code output in my jenkins console log
