### ISSUE TITLE
blackBright is throwing an error

### ISSUE THREAD

**Issue by Flynnp25** [chalk/chalk#352]
How to reproduce:
const chalk = require('chalk');
const log = console.log;

log(chalk.blackBright('blackBright'));

Error in console:
log(chalk.blackBright('blackBright'));
          ^

TypeError: chalk.blackBright is not a function
    at Object.<anonymous> (C:\Projects\temp\index.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! temp@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the temp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paddy.flynn\AppData\Roaming\npm-cache\_logs\2019-07-03T15_54_21_270Z-debug.log

Attached is list of colors from install chalk package.
Blackbright is a color option.
![Capture](https://user-images.githubusercontent.com/7794028/60606728-ca490280-9db3-11e9-8e3f-cd50561d10ca.PNG)

**Comment by sindresorhus** [comment]
`blackBright` is only available in the upcoming v3 version. It's a mistake that it's in the TS definition for v2.

**Comment by sgatade** [comment]
It would help to comment it out in index.d.ts?

![image](https://user-images.githubusercontent.com/13362030/62409633-a78c5280-b5da-11e9-9d31-9e1cf4a60c06.png)

**Comment by sindresorhus** [comment]
v3 is now out: https://github.com/chalk/chalk/releases/tag/v3.0.0
