### ISSUE TITLE
error

### ISSUE THREAD

**Issue by parvezmehdi** [chalk/chalk#394]
when we run androidjs init  getting below error

C:\Users\suppo\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\chalk\source\index.js:103
        ...styles,
        ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\suppo\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\inquirer\lib\objects\separator.js:2:13)

**Comment by sindresorhus** [comment]
This package requires Node.js 10 or later.

**Comment by parvezmehdi** [comment]
thanks install Node.js latest version problem solved
