### ISSUE TITLE
Yarn PnP fails to resolve #ansi-styles

### ISSUE THREAD

**Issue by stevenxu-db** [chalk/chalk#531]
Yarn PnP appears to fail with chalk 5. A routine import of chalk fails with the following message:

```
(node:28002) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/private/var/folders/4y/p9httzjd7px11pkmsfvlbdym0000gp/T/tmp.i44UjSW8/.pnp.cjs:9361
  return Object.defineProperties(new Error(message), {
                                 ^

Error: chalk tried to access #ansi-styles, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: #ansi-styles (via "#ansi-styles/package.json")
Required by: chalk@npm:5.0.0 (via /private/var/folders/4y/p9httzjd7px11pkmsfvlbdym0000gp/T/tmp.i44UjSW8/.yarn/cache/chalk-npm-5.0.0-7be183234e-6eba7c518b.zip/node_modules/chalk/source/index.js)

    at internalTools_makeError (/private/var/folders/4y/p9httzjd7px11pkmsfvlbdym0000gp/T/tmp.i44UjSW8/.pnp.cjs:9361:34)
    at resolveToUnqualified (/private/var/folders/4y/p9httzjd7px11pkmsfvlbdym0000gp/T/tmp.i44UjSW8/.pnp.cjs:10659:21)
    at Object.resolveToUnqualified (/private/var/folders/4y/p9httzjd7px11pkmsfvlbdym0000gp/T/tmp.i44UjSW8/.pnp.cjs:10856:26)
    at resolve$1 (file:///private/var/folders/4y/p9httzjd7px11pkmsfvlbdym0000gp/T/tmp.i44UjSW8/.pnp.loader.mjs:195:31)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The same works fine with node-modules linker. This may be related to `package.json` `imports` introduced in v5: https://github.com/chalk/chalk/blob/4d5c4795ad24c326ae16bfe0c39c826c732716a9/package.json#L10.

Repro steps:

```
tmp="$(mktemp -d)"
cd "$tmp"
yarn set version berry
echo '{"type": "module"}' > package.json
echo """import chalk from 'chalk';
console.log(chalk.blue('hi'));""" > index.js
yarn add chalk@^5
yarn node ./index.js # fails

### other test cases follow

yarn config set nodeLinker node-modules
yarn
yarn node ./index.js # works

yarn config set nodeLinker pnp
yarn
yarn node ./index.js # fails

yarn up chalk@^4
yarn
yarn node ./index.js # works
```

Environment:

```
$ yarn -v; node -v; uname -a
1.22.15
v16.13.1
Darwin C02FC0SHMD6R 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
```

**Comment by sindresorhus** [comment]
This is a problem with Yarn PnP and should be reported on the Yarn issue tracker.

**Comment by Kurt-von-Laven** [comment]
I encountered the same issue and recently discovered that adding the following section to `.yarnrc.yml` works around the matter:

```yaml
packageExtensions:
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": npm:ansi-styles@6.1.0
      "#supports-color": npm:supports-color@9.2.2
```

**Comment by dobesv** [comment]
Steps to reproduce:

```
$ mkdir chalk-err
$ cd chalk-err
$ yarn init
yarn init v1.22.19
question name (chalk-err): 
question version (1.0.0): 
question description: 
question entry point (index.js): 
question repository url: 
question author: 
question license (MIT): 
question private: 
success Saved package.json
Done in 5.67s.
$ yarn set version berry
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.2.3/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.2.3.cjs
➤ YN0000: Done in 0s 547ms
$ yarn add chalk
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ chalk@npm:5.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 155ms
$ yarn node
Welcome to Node.js v16.17.0.
Type ".help" for more information.
> import('chalk')
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 157,
  [Symbol(trigger_async_id_symbol)]: 11
}
> Uncaught:
Error: chalk tried to access #ansi-styles, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: #ansi-styles (via "#ansi-styles/package.json")
Required by: chalk@npm:5.0.1 (via /home/ubuntu/chalk-err/.yarn/cache/chalk-npm-5.0.1-6afcb94227-7b45300372.zip/node_modules/chalk/source/index.js)

    at makeError (/home/ubuntu/chalk-err/.pnp.cjs:8466:34)
    at resolveToUnqualified (/home/ubuntu/chalk-err/.pnp.cjs:9385:21)
    at Object.resolveToUnqualified (/home/ubuntu/chalk-err/.pnp.cjs:9529:26)
    at resolve$1 (file:///home/ubuntu/chalk-err/.pnp.loader.mjs:224:31)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
> 

```

**Comment by Qix-** [comment]
We're well aware of the issue - `yarn` lacks proper support for how we structure our package.json.

There's nothing actionable here. Please voice your support for this feature over at the appropriate Yarn repository.
