### ISSUE TITLE
chalk 5.x fails with typescript

### ISSUE THREAD

**Issue by drernie** [chalk/chalk#613]
The current 5.x version of chalk does not appear to work with typescript.
Here is an example project that works great with v4.x, but fails catastrophically when upgrading to 5.x:

https://github.com/TheSwanFactory/ts-cli/issues/5
https://github.com/TheSwanFactory/ts-cli/tree/5-chalk-5x-fails-with-typescript

**Comment by drernie** [comment]
The error message is:
```
const chalk = require("chalk");
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/ernest/Developer/ts-cli/node_modules/chalk/source/index.js from /Users/ernest/Developer/ts-cli/dist/src/utils.js not supported.
Instead change the require of index.js in /Users/ernest/Developer/ts-cli/dist/src/utils.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/ernest/Developer/ts-cli/dist/src/utils.js:14:15)
    at Object.<anonymous> (/Users/ernest/Developer/ts-cli/dist/src/index.js:4:17) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.5.1
```

This is from the generated JavaScript. The original TypeScript uses:
```
import * as chalk from "chalk";
```

I can't find any combination that *does* work.

**Comment by drernie** [comment]
I suppose this may be a TypeScript issue, but they appear to have punted:

https://github.com/microsoft/TypeScript/issues/46930

This issue appears to be well-known on the Internet, but apparently nobody filed a ticket before ;-{

* https://stackoverflow.com/questions/70309135/chalk-error-err-require-esm-require-of-es-module

I will look into the ESM discussion to see if that helps...

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by drernie** [comment]
Oh, I guess this issue came up before, sorry:

https://github.com/chalk/chalk/issues/527
